# Changes here will be overwritten by Copier
_commit: '3730359'
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: true
email: nick@koston.org
full_name: J. Nick Koston
github_username: bluetooth-devices
has_cli: false
initial_commit: true
open_source_license: MIT
package_name: uart_devices
project_name: uart-devices
project_short_description: UART Devices for Linux
project_slug: uart-devices
run_poetry_install: true
setup_github: true
setup_pre_commit: true

